### ISSUE TITLE
leaveTeam

### ISSUE THREAD

**Issue by Feier68** [gigaclub/BuilderSystemAPI#2]
bitte Team Auswahl welches man leaven soll  oder will

**Comment by Feier68** [comment]
das gleiche für kickMember , addMember , promoteMember , demoteMember

**Comment by kevinxdev** [comment]
@Feier68 Man kann nur einem Team angehören. Somit ist eine Auswahl unnötig, da einfach das Team verwendet wird, dem der User angehört.
