### ISSUE TITLE
entfernen von world id 

### ISSUE THREAD

**Issue by Feier68** [gigaclub/BuilderSystemAPI#21]
dafür world name

**Comment by kevinxdev** [comment]
@Feier68 macht denke ich überhaupt keinen Unterschied für deinen Code.

**Comment by Feier68** [comment]
@KevTVKevin 
 dann sag mir wie ich das mit den ids machen soll
k.a wie ich das hinbekommen soll

**Comment by kevinxdev** [comment]
> @Feier68 macht denke ich überhaupt keinen Unterschied für deinen Code.
> 

@Feier68 wie wolltest du es mit den Namen machen?

**Comment by Feier68** [comment]
Name abfragen
Erstellen aus Task und Team Name

**Comment by kevinxdev** [comment]
> Name abfragen
> Erstellen aus Task und Team Name
